default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: table_progress_development

test:
  <<: *default
  database: table_progress_test

production:
  url: <%= ENV['DATABASE_URL'] %>
